### ISSUE TITLE
Falha ao recuperar idPlano em Dominios Informações

### ISSUE THREAD

**Issue by abaif** [kinghost/API-PHP#1]
Em Dominios::getDadosDominio, o resultado não informa o planoId, não importa qual dominio seja, tente com todos os domínios da revenda e em todos o $result['body'][X]['planoId'] retornou string(0) "".

**Comment by fbraz3** [comment]
Olá,

Primeiramente peço desculpas pela resposta tão tardia, porém o projeto da API está sendo retomado e estou nesse momento verificando essas issues antigas.

Segundo verifiquei usando uma conta de teste o campo PlanoId está retornando corretamente, talvez seja (ou tenha sido, dado tempo de abertura da issue) alguma questão específica em sua revenda.

Para report de issues, o ideal é a utilização do painel de controle da KingHost ao qual dispõe de equipes trabalhando em regime de 24/7
