### ISSUE TITLE
Erro ao remover um multi redirecionamento de um email

### ISSUE THREAD

**Issue by brhrmaster** [kinghost/API-PHP#4]
Ao adicionar/editar um multi-redirecionamento de qualquer e-mail utilizando o PUT /email/editredir funciona como esperado. Como faço agora para remover os emails adicionados??? Ao mandar chamar a rotina sem nenhum destino, tenho um "fail". Já no DELETE /email/removeredir/$idDominio/$email me indica que estaria removendo (excluindo) um redirecionamento do tipo Alias da minha conta e não é isso que preciso.

**Comment by fbraz3** [comment]
Olá,

Primeiramente peço desculpas pela resposta tão tardia, porém o projeto da API está sendo retomado e estou nesse momento verificando essas issues antigas.

Do ponto de vista técnico o "múltiplos recebimentos" e o alias de emails são muito parecidos.
Para o postfix, toda a caixa postal possui um alias que aponta para ele mesmo (incrível que não cause um loop, mas é assim mesmo que funciona),  para "múltiplos recebimentos" vai haver esse alias para a própria caixa e mais um (ou vários) email(s) configurado(s), deste modo o método que adiciona um alias e o que adiciona os múltiplos recebimentos utilizam o mesmo método, pois o que diferencia ambos basicamente é a presença de uma caixa postal física vinculada.

Deste modo, embora não haja uma chamada específica, se você utilizar o método para edição de alias passando como destino somente a propria caixa postal, o multiplo recebimento é automaticamente removido.

Abaixo exemplo de código que poderá utiulizar para isso:

```
require_once 'Email.php';
$kinghost = new Email('login@dominio.com.br', 'XXXXXXXXXX');

$param = array(
    'idDominio'    => XXXXX,
    'caixa'        => 'dominio@dominio.com.br',
    'destino'      => 'email1@dominio.com.br,email2@dominio.com.br,email3@dominio.com.br,email4@dominio.com.br'
);

// Adicionar vários "multiplos recebimentos"
$r = $kinghost->addMulti($param);
var_dump($r);

// Retornar ao estado original
$param['destino'] = 'dominio@dominio.com.br';
$r = $kinghost->addMulti($param);
var_dump($r);
```

Para report de issues, o ideal é a utilização do painel de controle da KingHost ao qual dispõe de equipes trabalhando em regime de 24/7
