### ISSUE TITLE
Cliente->autenticaCliente($param) deveria retornar idCliente em seu->responseBody

### ISSUE THREAD

**Issue by fabiomsb** [kinghost/API-PHP#5]
`Cliente->autenticaCliente($param)` poderia retornar `[idCliente]` em seu->`responseBody` para poder usarmos em `Cliente->getClientes($idCliente)` (https://api.kinghost.net/cliente/idCliente) ou implementar `Cliente->getClientes($idCliente)` para aceitar `$clienteEmail` e `$clienteCPFCNPJ` como `$param` para retornar um cliente específico.

No meu caso: `Cliente->getClientes()` está cada vez mais lento porque o `(array)$responseBody` [body] - que retorna a lista de todos os clientes - cresceu o suficiente para tanto. Ex.:
```
Array
(
    [status] => ok
    [body] => Array
                    ( [...] muitos clientes [...] )
)
```
Na forma atual, o único meio que tenho é baixar toda a lista de clientes [https://api.kinghost.net/cliente/] para filtrá-la ao cliente que me interessa e poder chamar `Cliente->doCall('cliente/'.$idCliente, '', 'GET')`.

**Comment by diegoper37** [comment]
Olá fábio,

Primeiramente obrigado pela sugestão, foi adicinado ao retordo 
do método autenticaCliente o Id do cliente em questão.

**Comment by fabiomsb** [comment]
Perfeito!
Muito obrigado!

**Comment by fabiomsb** [comment]
Após a correção do método PUT [https://github.com/kinghost/API-PHP/commit/268446d24f2dbfd92c1caa6c25ee42fbdd4b0170], `Cliente->autenticaCliente($param)` voltou retornar a string `'Cliente autenticado com sucesso.'` em `[body]` de seu->`responseBody`, quando `[status]` retorna `'ok'`.

Ficaria muito agradecido se `[body]` voltasse a retornar o `[idCliente]` do e-mail que está sendo autenticado como foi feito por @diegoper37 em outubro/2015.
