### ISSUE TITLE
Criar integração com o composer

### ISSUE THREAD

**Issue by rdehnhardt** [kinghost/API-PHP#6]
Atualmente o composer é uma das ferramentas para gerenciamento de dependências do PHP, por este motivo, seria de extrema utilidade a KingHost disponibilizar o package via composer, para ficar algo mais ou menos dessa maneira!

composer require kinghost/API-PHP

**Comment by fbraz3** [comment]
Olá,

Primeiramente peço desculpas pela resposta tão tardia, porém o projeto da API está sendo retomado e estou nesse momento verificando essas issues antigas.

O suporte ao composer foi adicionado, você pode carregar diretamente do github cadastrando, no seu composer.json, o repositorio antes do require, veja o exemplo abaixo:

```
"repositories": [   
    {
      "type": "git",
      "url": "https://github.com/kinghost/API-PHP"
    },   
  ],
 "require": {
    "kinghost/api-php": "dev-master",
  },
```
Lembrando que para report de issues, o ideal é a utilização do painel de controle da KingHost ao qual dispõe de equipes trabalhando em regime de 24/7
